const express = require('express');
const cors = require('cors');
const dotenv = require("dotenv").config();
const colors = require('colors');
const PORT = process.env.PORT || 5000;
const connectDB = require("./config/db");
const { errorMiddleware } = require("./middlewares/errorMiddleware");
const authRoute = require("./routes/authRoute");
const userRoute = require("./routes/userRoute");
const postRoute = require("./routes/postRoute");
const commentsRoute = require("./routes/commentRoute");
connectDB();
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cors());
app.use("/api/auth", authRoute);
app.use("/api/user", userRoute);
app.use("/api/post", postRoute);
app.use("/api/comment", commentsRoute);
app.use(errorMiddleware);
app.listen(PORT, () => { 
    console.log(`Server is listening on port ${PORT}`);
});